# =============================================================================
#  build-offline.ps1  -  Full offline .exe build for PoS Number One
# =============================================================================

$ErrorActionPreference = "Stop"
$Root    = $PSScriptRoot
$Client  = Join-Path $Root "client"
$Server  = Join-Path $Root "server"
$Desktop = Join-Path $Root "desktop"
$Sidecar = Join-Path $Desktop "sidecar"

$env:GENERATE_SOURCEMAP = "false"
# NODE_ENV must NOT be "production" here. npm omits devDependencies when it is,
# which silently strips @angular/cli (client) and prisma/pkg (server) from the
# installs below -- the "@angular/cli failed to install" failure. The shipped
# server gets NODE_ENV=production at RUNTIME from server/.env.offline; the
# Angular production build comes from --configuration offline. Neither needs it
# set here. Forced to "development" (not just left unset) so an inherited
# machine-level NODE_ENV=production cannot poison the installs either.
$env:NODE_ENV = "development"
$env:CARGO_INCREMENTAL = "1"

# Cargo writes tens of thousands of files into target/. Inside a OneDrive-synced
# folder OneDrive takes locks mid-sync and build scripts fail with
# "output path is not a writable directory". Build outside the synced tree.
if (-not $env:CARGO_TARGET_DIR -and $Root -like "*OneDrive*") {
    $env:CARGO_TARGET_DIR = Join-Path $env:LOCALAPPDATA "pos-patisserie-cargo-target"
    Write-Host "OneDrive path detected - building Rust into $env:CARGO_TARGET_DIR" -ForegroundColor Yellow
}
if ($env:CARGO_TARGET_DIR) {
    $BundleDir = Join-Path $env:CARGO_TARGET_DIR "release\bundle\nsis"
} else {
    $BundleDir = Join-Path $Desktop "src-tauri\target\release\bundle\nsis"
}

function Step($msg) {
    Write-Host ""
    Write-Host "========================================================" -ForegroundColor Cyan
    Write-Host "  $msg" -ForegroundColor Cyan
    Write-Host "========================================================" -ForegroundColor Cyan
}

# -- STEP 0 : Generate .env.offline + preflight -------------------------------
# .env.offline holds a JWT secret, so it is NOT committed. Generate it here with
# a fresh random secret when absent, so CI and clean clones work without one.
$envOffline = Join-Path $Server ".env.offline"
if (-not (Test-Path $envOffline)) {
    $bytes = New-Object byte[] 48
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    $secret = [Convert]::ToBase64String($bytes)
    $content = @"
# Offline / desktop mode environment - GENERATED by build-offline.ps1
DATABASE_URL="file:./pos_patisserie.db"
JWT_SECRET=$secret
PORT=3255
NODE_ENV=production
CLIENT_URL=http://localhost:3255
LOG_LEVEL=warn
"@
    [System.IO.File]::WriteAllText($envOffline, $content, (New-Object System.Text.UTF8Encoding($false)))
    Write-Host "Generated server/.env.offline with a fresh JWT_SECRET" -ForegroundColor Yellow
}

Step "0/7  Preflight - verifying offline build inputs exist"
$required = @(
    (Join-Path $Client "angular.json"),
    (Join-Path $Client "src\environments\environment.offline.ts"),
    (Join-Path $Server "src\index.offline.js"),
    (Join-Path $Server ".env.offline"),
    (Join-Path $Server "pkg.config.json"),
    (Join-Path $Server "prisma\schema.sqlite.prisma"),
    (Join-Path $Desktop "src-tauri\tauri.conf.json"),
    (Join-Path $Desktop "app-config.json")
)
$missing = $required | Where-Object { -not (Test-Path $_) }
if ($missing) {
    Write-Host "Missing required build inputs:" -ForegroundColor Red
    $missing | ForEach-Object { Write-Host "  - $_" -ForegroundColor Red }
    throw "Build inputs missing. If these exist locally they are untracked - CI builds from HEAD."
}
$ngJson = Get-Content (Join-Path $Client "angular.json") -Raw | ConvertFrom-Json
$buildCfgs = $ngJson.projects.'pos-patisserie'.architect.build.configurations
if (-not ($buildCfgs.PSObject.Properties.Name -contains "offline")) {
    throw "angular.json has no 'offline' build configuration - it is probably uncommitted."
}
Write-Host "All offline build inputs present" -ForegroundColor Green

# -- STEP 1 : Client dependencies ---------------------------------------------
Step "1/7  Installing client npm dependencies"
Set-Location $Client

# Remove everything to start fresh
if (Test-Path "node_modules") {
    Write-Host "Removing node_modules..." -ForegroundColor Yellow
    Remove-Item -Recurse -Force "node_modules" -ErrorAction SilentlyContinue
    # On a OneDrive-synced folder, OneDrive can hold a lock on a file mid-sync
    # and silently block the delete above (-ErrorAction SilentlyContinue eats
    # the error). npm would then "install" on top of a half-deleted tree and
    # only add a handful of packages instead of doing a real clean install --
    # which is exactly what breaks "ng" / @angular/cli further down. Fail
    # loudly here instead of limping into a corrupted install.
    if (Test-Path "node_modules") {
        throw "Could not fully remove client/node_modules (likely OneDrive holding a file lock). Close/pause OneDrive (or move this project outside the OneDrive folder) and re-run."
    }
}
if (Test-Path "package-lock.json") {
    Remove-Item -Force "package-lock.json" -ErrorAction SilentlyContinue
    if (Test-Path "package-lock.json") {
        throw "Could not remove client/package-lock.json (likely OneDrive holding a file lock). Close/pause OneDrive and re-run."
    }
}

Write-Host "Installing all client packages (3-5 minutes, ignore peer warnings)..." -ForegroundColor Cyan
# NOTE: no "2>&1 | Out-Default" here on purpose -- under $ErrorActionPreference
# = "Stop", merging a native command's stderr into the pipeline makes
# PowerShell treat every line npm writes to stderr (even harmless "npm warn"
# lines) as a terminating error and abort the whole script immediately.
# The $LASTEXITCODE check right below is what actually detects failure.
npm install --legacy-peer-deps --no-audit --no-fund
if ($LASTEXITCODE -ne 0) {
    throw "Client npm install failed - see errors above"
}

# Verify @angular/cli was installed
$ngPath = "node_modules\.bin\ng.cmd"
if (-not (Test-Path $ngPath)) {
    Write-Host "ERROR: Angular CLI not found. Trying manual install..." -ForegroundColor Red
    npm install @angular/cli@19.2.15 --save-dev --legacy-peer-deps --no-audit
    if (-not (Test-Path $ngPath)) {
        # Dump enough state here to actually diagnose this instead of guessing --
        # this exact check has failed multiple times for reasons that didn't
        # reproduce locally, so surface everything relevant before throwing.
        Write-Host "---- DIAGNOSTICS ----" -ForegroundColor Magenta
        Write-Host "node: $(node -v)   npm: $(npm -v)"
        $pkgCount = 0
        if (Test-Path "node_modules") { $pkgCount = (Get-ChildItem node_modules -Directory -ErrorAction SilentlyContinue).Count }
        Write-Host "node_modules top-level dir count: $pkgCount"
        $cliDir = "node_modules\@angular\cli"
        if (Test-Path $cliDir) {
            Write-Host "node_modules/@angular/cli exists. Contents:"
            Get-ChildItem $cliDir -ErrorAction SilentlyContinue | Select-Object Name | Format-Table -AutoSize | Out-String | Write-Host
            $cliPkg = Join-Path $cliDir "package.json"
            if (Test-Path $cliPkg) {
                $cliVersion = (Get-Content $cliPkg -Raw | ConvertFrom-Json).version
                Write-Host "@angular/cli installed version: $cliVersion"
            }
        } else {
            Write-Host "node_modules/@angular/cli does NOT exist at all."
        }
        if (Test-Path "node_modules\.bin") {
            Write-Host "node_modules/.bin contents matching ng*:"
            Get-ChildItem "node_modules\.bin" -Filter "ng*" -ErrorAction SilentlyContinue | Select-Object Name | Format-Table -AutoSize | Out-String | Write-Host
        } else {
            Write-Host "node_modules/.bin does NOT exist at all."
        }
        Write-Host "---------------------" -ForegroundColor Magenta
        throw "@angular/cli failed to install - check network/npm registry"
    }
}

$pkgCount = (Get-ChildItem node_modules -Directory).Count
Write-Host "Client dependencies installed ($pkgCount packages)" -ForegroundColor Green

# -- STEP 2 : Build Angular (offline config) ----------------------------------
Step "2/7  Building Angular offline"
Set-Location $Client
# Wipe dist first: on OneDrive-synced folders, letting the Angular CLI rmdir
# stale files mid-build races with OneDrive/AV file locks and throws EPERM.
# Building into an already-empty folder avoids that rmdir entirely.
if (Test-Path "dist") {
    Remove-Item -Recurse -Force "dist" -ErrorAction SilentlyContinue
}
npm run ng -- build --configuration offline --source-map false
if ($LASTEXITCODE -ne 0) {
    throw "Angular build failed"
}
Write-Host "Angular build complete" -ForegroundColor Green

# -- STEP 3 : Server dependencies ---------------------------------------------
Step "3/7  Installing server npm dependencies"
Set-Location $Server

if (Test-Path "node_modules") {
    Write-Host "Removing node_modules..." -ForegroundColor Yellow
    Remove-Item -Recurse -Force "node_modules" -ErrorAction SilentlyContinue
    if (Test-Path "node_modules") {
        throw "Could not fully remove server/node_modules (likely OneDrive holding a file lock). Close/pause OneDrive (or move this project outside the OneDrive folder) and re-run."
    }
}
if (Test-Path "package-lock.json") {
    Write-Host "Removing package-lock.json..." -ForegroundColor Yellow
    Remove-Item -Force "package-lock.json" -ErrorAction SilentlyContinue
    if (Test-Path "package-lock.json") {
        throw "Could not remove server/package-lock.json (likely OneDrive holding a file lock). Close/pause OneDrive and re-run."
    }
}

npm install --legacy-peer-deps --no-audit --no-fund
if ($LASTEXITCODE -ne 0) {
    throw "Server npm install failed"
}

# Verify prisma was installed
if (-not (Test-Path "node_modules\prisma")) {
    throw "prisma not installed - check for npm errors above"
}

Write-Host "Server dependencies installed ($((Get-ChildItem node_modules -Directory).Count) packages)" -ForegroundColor Green

# -- STEP 4 : Generate Prisma SQLite client -----------------------------------
Step "4/7  Generating Prisma SQLite client"
Set-Location $Server
npm run db:generate:sqlite
if ($LASTEXITCODE -ne 0) {
    throw "Prisma generate failed"
}
Write-Host "Prisma client generated" -ForegroundColor Green

# -- STEP 4b : Template SQLite database ---------------------------------------
# A fresh install gets an empty .db and every query fails with
# "The table main.users does not exist". Build a template here (schema + seed)
# and ship it; index.offline.js copies it into place on first run.
Step "4b/7  Building template SQLite database (schema + seed)"
$TemplateDb = Join-Path $Server "pos_patisserie.template.db"
Remove-Item $TemplateDb -Force -ErrorAction SilentlyContinue
$savedDbUrl = $env:DATABASE_URL
$env:DATABASE_URL = "file:$TemplateDb"
npx prisma db push --schema=prisma/schema.sqlite.prisma --skip-generate --accept-data-loss
if ($LASTEXITCODE -ne 0) { throw "prisma db push failed while building the template database" }
Copy-Item (Join-Path $Server "prisma\seed.js") (Join-Path $Server "prisma\seed.mjs") -Force
node prisma/seed.mjs
$seedCode = $LASTEXITCODE
Remove-Item (Join-Path $Server "prisma\seed.mjs") -Force -ErrorAction SilentlyContinue
$env:DATABASE_URL = $savedDbUrl
if ($seedCode -ne 0) { throw "Seeding the template database failed" }
if (-not (Test-Path $TemplateDb)) { throw "Template database was not created" }
Write-Host "Template database built (admin PIN 1100)" -ForegroundColor Green

# -- STEP 5 : Bundle server -> pos-server.exe ---------------------------------
Step "5/7  Bundling Express server with pkg"

New-Item -ItemType Directory -Force -Path $Sidecar | Out-Null

$pkgCheck = Get-Command pkg -ErrorAction SilentlyContinue
if ($pkgCheck) {
    npx --yes @yao-pkg/pkg src/index.offline.js --config pkg.config.json --target node22-win-x64 --output "$Sidecar\pos-server.exe" --compress GZip
} else {
    Write-Host "pkg not found globally, using npx..." -ForegroundColor Yellow
    npx --yes @yao-pkg/pkg src/index.offline.js --config pkg.config.json --target node22-win-x64 --output "$Sidecar\pos-server.exe" --compress GZip
}

if ($LASTEXITCODE -ne 0) {
    throw "pkg bundling failed"
}
Write-Host "Server bundled -> $Sidecar\pos-server.exe" -ForegroundColor Green

# -- STEP 6 : Copy sidecar (.exe + .env.offline) into desktop/resources ------
# IMPORTANT: tauri.conf.json only bundles files from desktop/resources/*
# (see "bundle.resources"). The pkg output above lands in desktop/sidecar/,
# which Tauri never packages on its own -- without this copy, the installer
# would silently ship whatever pos-server.exe happened to already be sitting
# in desktop/resources (a stale build), not the one just compiled.
Step "6/7  Copying sidecar into desktop/resources (what Tauri actually bundles)"
Copy-Item -Force "$Server\.env.offline" "$Sidecar\.env.offline"
$Resources = Join-Path $Desktop "resources"
New-Item -ItemType Directory -Force -Path $Resources | Out-Null
Copy-Item -Force "$Sidecar\pos-server.exe" "$Resources\pos-server.exe"
Copy-Item -Force "$Sidecar\.env.offline" "$Resources\.env.offline"

# sharp's native binaries can't be embedded in the pkg snapshot (pkg prints a
# "must be distributed with executable" warning for these two folders) --
# they have to sit on disk next to pos-server.exe as loose files.
# sharp >= 0.33 no longer ships sharp/build/Release + sharp/vendor/lib. The
# prebuilt native module lives in its own package (@img/sharp-win32-x64).
# The old paths did not exist, and -ErrorAction SilentlyContinue made the
# copies fail silently -- the installer shipped with no sharp binary at all.
$SharpSrc = Join-Path $Server "node_modules\sharp"
$ImgSrc   = Join-Path $Server "node_modules\@img"
if (-not (Test-Path $ImgSrc)) {
    throw "server/node_modules/@img not found - sharp native prebuild missing."
}
Write-Host "Copying sharp native binaries next to pos-server.exe..." -ForegroundColor Cyan
$ResNM = Join-Path $Resources "node_modules"
New-Item -ItemType Directory -Force -Path $ResNM | Out-Null
Copy-Item -Recurse -Force $ImgSrc (Join-Path $ResNM "@img")
Copy-Item -Recurse -Force $SharpSrc (Join-Path $ResNM "sharp")
$imgCopied = (Get-ChildItem (Join-Path $ResNM "@img") -Recurse -Filter "*.node" -ErrorAction SilentlyContinue).Count
if ($imgCopied -lt 1) {
    throw "Copied @img but found no .node binary - sharp will fail at runtime."
}
# The server reads/writes these next to the exe (settings, roles, logos).
# They live inside the pkg snapshot otherwise, which is read-only.
New-Item -ItemType Directory -Force -Path (Join-Path $Resources "uploads") | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $Resources "src\uploads") | Out-Null
Copy-Item -Recurse -Force (Join-Path $Server "uploads\*")     (Join-Path $Resources "uploads")     -ErrorAction SilentlyContinue
Copy-Item -Recurse -Force (Join-Path $Server "src\uploads\*") (Join-Path $Resources "src\uploads") -ErrorAction SilentlyContinue
# Identifiant de build : le serveur le compare a installed-build.txt et,
# s'ils different, archive les donnees puis repart d'une base vierge.
$buildId = (Get-Date -Format "yyyyMMdd-HHmmss")
try { $sha = (git -C $Root rev-parse --short HEAD 2>$null); if ($sha) { $buildId = "$buildId-$sha" } } catch {}
[System.IO.File]::WriteAllText((Join-Path $Resources "build-id.txt"), $buildId, (New-Object System.Text.UTF8Encoding($false)))
Write-Host "Build ID : $buildId" -ForegroundColor Green
Copy-Item -Force (Join-Path $Server "pos_patisserie.template.db") (Join-Path $Resources "pos_patisserie.template.db")
Write-Host "sharp native binaries copied ($imgCopied .node file(s))" -ForegroundColor Green
Write-Host "Sidecar copied to desktop/resources" -ForegroundColor Green

# -- STEP 7a : WebView2 offline installer -------------------------------------
Step "7a/7  Checking WebView2 offline installer"
$wv2Path = Join-Path $Desktop "src-tauri\WebView2RuntimeInstaller.exe"
if (-not (Test-Path $wv2Path)) {
    Write-Host "Downloading WebView2 offline installer (~120 MB)..." -ForegroundColor Yellow
    $wv2Url = "https://go.microsoft.com/fwlink/p/?LinkId=2124703"
    Invoke-WebRequest -Uri $wv2Url -OutFile $wv2Path -UseBasicParsing
    Write-Host "WebView2 installer downloaded" -ForegroundColor Green
} else {
    Write-Host "WebView2 installer already present - skipping" -ForegroundColor Green
}

# -- STEP 7b : Build Tauri .exe installer -------------------------------------
Step "7b/7  Building Tauri desktop installer"
Set-Location $Desktop

$tauriCmd = Get-Command "cargo-tauri" -ErrorAction SilentlyContinue
if ($tauriCmd) {
    cargo tauri build
} else {
    npx --yes @tauri-apps/cli@2 build
}

if ($LASTEXITCODE -ne 0) {
    throw "Tauri build failed"
}

# -- Done ---------------------------------------------------------------------
Write-Host ""
Write-Host "========================================================" -ForegroundColor Green
Write-Host "  BUILD COMPLETE" -ForegroundColor Green
Write-Host "  Installer: $BundleDir" -ForegroundColor Green
Write-Host "  WebView2 bundled - no internet needed on target PC" -ForegroundColor Green
Write-Host "========================================================" -ForegroundColor Green
