-- AlterTable
ALTER TABLE `expenses` ADD COLUMN `collection_date` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `payment_type` ENUM('CASH', 'CHECK', 'BANK_TRANSFER', 'WIRE_TRANSFER') NOT NULL DEFAULT 'CASH';
