UPDATE produits_de_caisse SET id = 1  WHERE name = 'PETIT FOUR';
UPDATE produits_de_caisse SET id = 2  WHERE name = 'LOUZIA';
UPDATE produits_de_caisse SET id = 3  WHERE name = 'HLOU KAKAWIA';
UPDATE produits_de_caisse SET id = 4  WHERE name = 'BAKLAWA KAKWIA';
UPDATE produits_de_caisse SET id = 5  WHERE name = 'JALJLENIA';
UPDATE produits_de_caisse SET id = 6  WHERE name = 'CHOCOLAT KAKAWIA';
UPDATE produits_de_caisse SET id = 7  WHERE name = 'MARROCAIN';
UPDATE produits_de_caisse SET id = 8  WHERE name = 'MAACHAACH';
UPDATE produits_de_caisse SET id = 9  WHERE name = 'HLOU LOUZ';
UPDATE produits_de_caisse SET id = 10 WHERE name = 'BJEWIYA';
UPDATE produits_de_caisse SET id = 11 WHERE name = 'BAKLAWA AMANDE';
UPDATE produits_de_caisse SET id = 12 WHERE name = 'MAKROUDH ASMAR';
UPDATE produits_de_caisse SET id = 13 WHERE name = 'HOMSIA';
UPDATE produits_de_caisse SET id = 14 WHERE name = 'MAKROUDH DRO3';
UPDATE produits_de_caisse SET id = 15 WHERE name = 'ABYADH NOISETTE';
UPDATE produits_de_caisse SET id = 15 WHERE name = 'GATEAUX SOWABAA';
UPDATE produits_de_caisse SET id = 16 WHERE name = 'SABLE';
UPDATE produits_de_caisse SET id = 17 WHERE name = 'SABLE';
UPDATE produits_de_caisse SET id = 18 WHERE name = 'CROCANT';
UPDATE produits_de_caisse SET id = 19 WHERE name = 'AJNAB BAKLAWA LOUZ';
UPDATE produits_de_caisse SET id = 20 WHERE name = 'AJNAB BAKLAWA KAKAWIA';
UPDATE produits_de_caisse SET id = 23 WHERE name = 'MARROCAIN AMANDE';